spring.application.name=backend


spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=ocean_view_resort_db
 
# Mailtrap Configuration
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=23e575503bd17b
spring.mail.password=6f1b21f8e60876
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true



# Security Configuration
oceanview.app.jwtSecret=oceanViewResortSecretKeyForJwtAuthenticationMustBeLongAndSecure
oceanview.app.jwtExpirationMs=86400000

# Google OAuth2 Configuration
# Get your Client ID from https://console.cloud.google.com/
google.client.id=707866377438-20640dlhedfh63fu8iqot6n8394vp9mo.apps.googleusercontent.com